### ISSUE TITLE
TypeError: LaserMix.__init__() got an unexpected keyword argument 'segmentor_student'

### ISSUE THREAD

**Issue by azhuantou** [ldkong1205/LaserMix#10]
Hi @ldkong1205 
When I run the following command:
python tools/train.py configs/lasermix/lasermix_cy3d_semi_semantickitti_10.py
the above error occurred.

Could you please help me?

**Comment by ldkong1205** [comment]
Hi @azhuantou, sorry for the confusion! I have just updated `semi_base.py`. The updates are [here](https://github.com/ldkong1205/LaserMix/commit/d2ebdd15e2657e5bb95e230bf1383c5c5c6f8139). Could you pull the updates and try again? Thanks!

**Comment by azhuantou** [comment]
Thanks for your quick reply!
It seems to still have the same error.

**Comment by ldkong1205** [comment]
Hi @azhuantou, sorry again ...  Made some updates on [this](https://github.com/ldkong1205/LaserMix/blob/main/mmdet3d/models/segmentors/lasermix.py) file as well. Would you mind trying again? Thanks!

**Comment by azhuantou** [comment]
Thanks for your attention. Error resolved,  but an important file (**semantickitti_infos_val.pkl**) is missing and I can not find it in the Google Drive you provided.

**Comment by ldkong1205** [comment]
Hi @azhuantou, thanks for letting me know!

The `semantickitti_infos_train.pkl` and `semantickitti_infos_val.pkl` file can be generated via the following command:
```
python ./tools/create_data.py semantickitti --root-path ./data/semantickitti --out-dir ./data/semantickitti --extra-tag semantickitti
```

I have updated [DATA_PREPARE.md](https://github.com/ldkong1205/LaserMix/blob/main/docs/DATA_PREPARE.md). Thanks for your reminder!

**Comment by azhuantou** [comment]
Thanks for your timely reply! All the problems have been resolved! :)

**Comment by ldkong1205** [comment]
> Thanks for your timely reply! All the problems have been resolved! :)

Glad to hear and appreciate your feedback~

Please don't hesitate to let us know if you have any further questions. Thanks!
