### ISSUE TITLE
KeyError LaserMix is not in the mmdet3d.

### ISSUE THREAD

**Issue by zhairf** [ldkong1205/LaserMix#15]
Thanks for the great work and release the codes.

When I trying to train with a single GPU and run the command “python tools/train.py configs/lasermix/lasermix_cy3d_semi_semantickitti_10.py”, got a KeyError: ‘LaserMix’ is not in the mmdet3d::model registry. Did I miss something when install process? What should I do to deal this problem?

Thank you very much.

**Comment by ldkong1205** [comment]
Hi @zhairf, thanks for reaching out!

The posted error seems related to the installation of `mmdet3d`. Have you followed the same procedures as listed in [INSTALL.md](https://github.com/ldkong1205/LaserMix/blob/main/docs/INSTALL.md)?

If the above installation is good, then you might want to re-install `mmdet3d` with `pip install -e .` or `python setup.py develop`. Can you try and let me know whether this works for you?

**Comment by ldkong1205** [comment]
Hi @zhairf, hope the above answer resolves your question. Free feel to let us know if you have further questions!

**Comment by zhairf** [comment]
Thank you very much. Your answer solved my problem.

**Comment by giddyyupp** [comment]
Hi,
following the guide for the installation of mmdetection3d does not solve this error for me. I tried both options both no luck, instead I installed lasermix:
```
cd LaserMix/
python -m pip install -v -e .
```
moreover you may need to change versions of mmcv and mmdet:
```
python -m mim install 'mmcv==2.0.0rc4'
python -m mim install 'mmdet==3.1.0'
```
