### ISSUE TITLE
AttributeError: 'PointData' object has no attribute 'voxel_semantic_mask'

### ISSUE THREAD

**Issue by molarsu** [ldkong1205/LaserMix#17]
Thanks for the great work and release the codes.
When I trying to train with a single GPU and run the command “python tools/train.py configs/lasermix/lasermix_minku18_semi_semantickitti_10.py”, got a AttributeError: 'PointData' object has no attribute 'voxel_semantic_mask'. Did you mean: 'pts_semantic_mask'? 
What should I do to deal this problem? 
Thank you very much.

**Comment by Xiangxu-0103** [comment]
Hi, thanks for your attention to our work. It's indeed a bug as we have refactored the structure of `MinkUNet`. We have updated the code. Please let us know if you face new problems.

**Comment by molarsu** [comment]
Thanks for your reply!
But I got a TypeError: super() takes no keyword arguments from File LaserMix/mmdet3d/models/segmentors/minkunet.py in line 24 , def __init__(self, **kwargs) -> None:  super(MinkUNet).__init__(**kwargs)
And when I fix it to super().__init__(**kwargs), it could work.

**Comment by Xiangxu-0103** [comment]
Thanks for your feedback again. It should be `super(MinkUNet, self).__init__(**kwargs)` and it will be fixed soon.

**Comment by molarsu** [comment]
Thanks for your reply and my problem has been solved!
