### ISSUE TITLE
Training log file for the nuScenes dataset

### ISSUE THREAD

**Issue by azhuantou** [ldkong1205/LaserMix#20]
Hi, @ldkong1205 @Xiangxu-0103  could you please show the training log file (lasermix_cy3d_semi_nuscenes_10.py) for the nuScenes dataset. I can not reproduce the results claimed in your paper, so I want to find out by comparing whether I did any steps wrong.

**Comment by ldkong1205** [comment]
Hi @azhuantou, kindly refer to the latest response in https://github.com/ldkong1205/LaserMix/issues/13. Thanks!

**Comment by azhuantou** [comment]
Thanks for your quick reply!
