### ISSUE TITLE
Generation script for semi dataset

### ISSUE THREAD

**Issue by molarsu** [ldkong1205/LaserMix#21]

**Comment by molarsu** [comment]
Thanks for your work and could you please show your generation script for the semi dataset like the python script to generate the  semantickitti_infos_train.1-unlabeled.pkl

**Comment by ldkong1205** [comment]
Hi @molarsu, thank you for your interest in this work, and sorry for the late response.

You can find an example of the split generation [here](https://github.com/ldkong1205/LaserMix/blob/main/tools/dataset_converters/semantickitti_converter.py#L80). Specifically, we random sample from the whole dataset with a predefined proportion, e.g., 10%, and separate them from the remaining scans to form the `labeled` and `unlabeled` .pkl files.

Hope the above helps! Let us know if you have further question.
