### ISSUE TITLE
Can this network run on datasets such as S3DIS and Toronto3D

### ISSUE THREAD

**Issue by mooncakehub** [ldkong1205/LaserMix#22]
Thank you for your great work.But I want to know that Can this network run on datasets such as S3DIS and Toronto3D

**Comment by ldkong1205** [comment]
> Thank you for your great work.But I want to know that Can this network run on datasets such as S3DIS and Toronto3D

Hi @mooncakehub, though I didn't try LaserMix on these two datasets, I believe it is promising. To the best of my knowledge, both S3DIS and Toronto3D have certain scene priors encoded and it is intuitive to mix along such priors to enhance the training.
