### ISSUE TITLE
can I run this code with four 2080Ti GPUs

### ISSUE THREAD

**Issue by mooncakehub** [ldkong1205/LaserMix#23]

**Comment by ldkong1205** [comment]
Hi @mooncakehub, thanks for your interest in this work!

The answer to your question is yes. You can choose a suitable segmentation backbone to fit the memory in your GPU machines. I list several options below for your reference:


| Backbone | Backend | Memory | Training Time | FPS |
| :-: | :-: | :-: | :-: | :-: |
| MinkUNet18-W16 | `torchsparse` | 3.4 GB | - | - |
| MinkUNet34-W32 | `minkowski engine` | 11.5 GB | 6.5 hours | 12.2 |
| MinkUNet34-W32 | `spconv` | 6.7 GB | 2.0 hours | 14.6 |
| Cylinder3D | `spconv` |  10.2 GB | - | - |

**Comment by mooncakehub** [comment]
Thank you for  your reply. it's really helpful
