### ISSUE TITLE
no such file or directory:'/data/sets/nuscenes/nuscenes_infos_train.10.pkl'

### ISSUE THREAD

**Issue by Borddy0** [ldkong1205/LaserMix#27]
Thanks for the great work and release the codes.

When I trying to train with a single GPU and run the command “python tools/train.py configs/lasermix/lasermix_cy3d_semi_nuscenes_10.py”, got a KeyError: no such file or directory:'/data/sets/nuscenes/nuscenes_infos_train.10.pkl'.  What should I do to deal this problem?

Thank you very much

**Comment by ldkong1205** [comment]
Hi @Borddy0, thanks for your interest in this work!

You can generate these `.pkl` files by following the steps listed in https://github.com/ldkong1205/LaserMix/blob/main/docs/DATA_PREPARE.md.
