### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by LinLin1031** [ldkong1205/LaserMix#29]
When will the training and evaluation details for LaserMix and LaserMix++ be released in full?

**Comment by ldkong1205** [comment]
> When will the training and evaluation details for LaserMix and LaserMix++ be released in full?

@LinLin1031, thanks for your interest!

The training and evaluation details of LaserMix using Cylinder3D and MinkUNet are available. We will include the support of other backbones and more details of LaserMix++ in the next few weeks.
