### ISSUE TITLE
About model weights initialization

### ISSUE THREAD

**Issue by hyalvin** [ldkong1205/LaserMix#32]
Hi, I wanna know whether I should use a pretrained segmentor (i.e., already fully trained on the supervised dataset) to initialize `teacher` or both `teacher` and `student` ? Or let them both be initialized as what supervised training does.

**Comment by ldkong1205** [comment]
> Hi, I wanna know whether I should use a pretrained segmentor (i.e., already fully trained on the supervised dataset) to initialize `teacher` or both `teacher` and `student` ? Or let them both be initialized as what supervised training does.

Hi @hyalvin, thanks for your interest in this project.

Can you describe more details about your object? If your model has been trained using full labels, why do you still need to consider semi-supervised learning?

**Comment by hyalvin** [comment]
Thanks for the timely reply! I am a greenhand of semi-supervised learning, and I wanna use huge number of unlabeled data to boost the model's performance (at the basis of supervised model).

**Comment by ldkong1205** [comment]
> Thanks for the timely reply! I am a greenhand of semi-supervised learning, and I wanna use huge number of unlabeled data to boost the model's performance (at the basis of supervised model).

Thanks for providing extra information. Our models (student and teacher) are initialized randomly, and then trained jointly using labeled and unlabeled data.

For your case, I believe it's OK to initialize the models with pretrained weights on labeled data, and then jointly train using labeled and unlabeled data.

**Comment by hyalvin** [comment]
Got it, thanks a lot!
