### ISSUE TITLE
Question about the backbone for LaserMix++.

### ISSUE THREAD

**Issue by azhuantou** [ldkong1205/LaserMix#35]
Thanks for your nice work!

I would like to ask whether the reported performance for LaseMix++ (with MinkUnet as the backbone) were generated by training using the released [config](https://github.com/ldkong1205/LaserMix/blob/main/configs/lasermix/lasermix_minku18_semi_semantickitti_10.py) file.

**Comment by ldkong1205** [comment]
Hi @azhuantou, sorry for the late reply!

For your question: 
- The reported performance of LaserMix++ (with MinkUNet as the backbone) was obtained following the same setup of LaserMix.
- The config files, which will be released soon, share the same setups as [this](https://github.com/ldkong1205/LaserMix/blob/main/configs/lasermix/lasermix_minku18_semi_semantickitti_10.py) config file, except for the newly added designs.

Should you have any other questions, please feel free to let us know!

**Comment by azhuantou** [comment]
Thank you for your response. I look forward to your open-source code !
