### ISSUE TITLE
The training details

### ISSUE THREAD

**Issue by kleinzcy** [ldkong1205/LaserMix#6]
Thanks your nice work. I am curious when you are convenient to release the training config.

**Comment by ldkong1205** [comment]
Hi @kleinzcy, Thanks for your interest in this work!

Which training config file are you looking for?

We are working on an extension of the previous framework; the new framework is with an instance mixing module and is expected to support LiDAR panoptic segmentation as well. The training details and model checkpoints will be made publicly available by next month.

**Comment by kleinzcy** [comment]
I am looking for semantickitti voxel lasermix. 

Looking forward your updated framework.

**Comment by ldkong1205** [comment]
Hi @kleinzcy, for training with LaserMix on SemanticKITTI using a voxel-based backbone, we recommend you first take a look at [this](https://github.com/open-mmlab/mmdetection3d/pull/2302) implementation in MMDetection3D. We have now supported training Cylinder3D, MinkUNet, and SPVCNN with LaserMix.

For the updated framework: We will try to finalize this as soon as possible and let you know once the upgrade is ready. Thanks for waiting!
