### ISSUE TITLE
Cylender3D Experiments

### ISSUE THREAD

**Issue by christy0621** [ldkong1205/LaserMix#7]
It is fine if you don't want to release the semi-supervised code. But is there any plan to release the supervised code of Cylender3D in the Nuscenes dataset?

-------------------
Edit:

I tried your setup (with a lower voxel grid size) based on the original Cylinder3D code https://github.com/xinge008/Cylinder3D, but the results are far lower than the results reported in your paper.

**Comment by ldkong1205** [comment]
Hi @christy0621, as mentioned previously (https://github.com/ldkong1205/LaserMix/issues/6), we are working on the journal extension of this work. The complete code should be out in the next several weeks.

For the results of Cylinder3D:
- Can you supplement more details for your question? Which voxel size did you use? What score did you get? How far lower are you implying?
- The reported results of Cylinder3D in the paper are reliable. We directly used the code from the authors (https://github.com/xinge008/Cylinder3D) in our implementation. I suggest you first try to reproduce the fully-supervised results from Cylinder3D.
- Two external resources that you could rely on, of which we have reproduced and achieved higher results than the original Cylinder3D reporting (and also the baselines in the LaserMix paper). Note that we have supported nuScenes in these two implementations but it should not be hard to adapt the code:
  - **MMDetection3D:** We have provided running scripts, logs, and model checkpoints at https://github.com/open-mmlab/mmdetection3d/tree/main/configs/cylinder3d. 
  - **PCSeg:**  We have provided the directly runnable commands and model checkpoints at https://github.com/open-mmlab/mmdetection3d/tree/main/configs/cylinder3d.

**Comment by ldkong1205** [comment]
Hi @christy0621, that's it. The current code for implementing Cylinder3D uses a `torchsparse` backend from SPVCNN, which is faster (in terms of both training and inference speed) not the performance becomes lower.

The results reported in the paper are from a `spconv 1.2.1` Cylinder3D, the same as the original implementation (https://github.com/xinge008/Cylinder3D). You should be able to reproduce the results by switching the backend back to `spconv`.

Our next update will include support for both backends, leaving room for you to choose between accuracy and efficiency. Please stay tuned for this update!
