### ISSUE TITLE
Confusion about the GET_STARTED.

### ISSUE THREAD

**Issue by azhuantou** [ldkong1205/LaserMix#9]
Hi, thanks for your great work.

I'm confused about how to start running this code and reproduce your results, do you have any plans to update GET_STARTED.MD.

Looking forward to your reply!

**Comment by ldkong1205** [comment]
Thanks for the reminder! The instructions will be updated this weekend.

**Comment by azhuantou** [comment]
Thanks for your quick reply!
Looking forward to your update.

**Comment by ldkong1205** [comment]
Hi @azhuantou, we have updated [INSTALL.md](https://github.com/ldkong1205/LaserMix/blob/main/docs/INSTALL.md) and [GET_STARTED.md](https://github.com/ldkong1205/LaserMix/blob/main/docs/GET_STARTED.md). Following the instructions, you should now be able to run training and evaluation of LaserMix on SemanticKITTI.

Feel free to reach us again if you encounter any issues in installing environment or running experiments.
